version: '3.8'

services:

  # SQL Server container
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: ATMServerDB
    environment:
      SA_PASSWORD: "AndreDb1@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  # .NET application container
  atm.api:
    image: ${DOCKER_REGISTRY-}atmapi
    build:
      context: .
      dockerfile: ATM.Api/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
